# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'NewTest-ServiceConn'
    subscriptionId: 'bae062a5-d86b-4b96-adca-1b82de20f65d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'NewTest'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/AzureDeploy.json'
    overrideParameters: -webAppName minlwlw123 
    deploymentMode: 'Incremental'
    deploymentName: 'davesDeployment'
